
package com.epam.lab.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalcServiceImpl", targetNamespace = "http://soap.service.lab.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalcServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.DivisionResponse")
    @Action(input = "http://soap.service.lab.epam.com/CalcServiceImpl/divisionRequest", output = "http://soap.service.lab.epam.com/CalcServiceImpl/divisionResponse")
    public String division(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "minus", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Minus")
    @ResponseWrapper(localName = "minusResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.MinusResponse")
    @Action(input = "http://soap.service.lab.epam.com/CalcServiceImpl/minusRequest", output = "http://soap.service.lab.epam.com/CalcServiceImpl/minusResponse")
    public String minus(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiple", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Multiple")
    @ResponseWrapper(localName = "multipleResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.MultipleResponse")
    @Action(input = "http://soap.service.lab.epam.com/CalcServiceImpl/multipleRequest", output = "http://soap.service.lab.epam.com/CalcServiceImpl/multipleResponse")
    public String multiple(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "percent", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Percent")
    @ResponseWrapper(localName = "percentResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.PercentResponse")
    @Action(input = "http://soap.service.lab.epam.com/CalcServiceImpl/percentRequest", output = "http://soap.service.lab.epam.com/CalcServiceImpl/percentResponse")
    public String percent(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "plus", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.Plus")
    @ResponseWrapper(localName = "plusResponse", targetNamespace = "http://soap.service.lab.epam.com/", className = "com.epam.lab.service.soap.PlusResponse")
    @Action(input = "http://soap.service.lab.epam.com/CalcServiceImpl/plusRequest", output = "http://soap.service.lab.epam.com/CalcServiceImpl/plusResponse")
    public String plus(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
