
package com.epam.lab.service.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalcServiceImplService", targetNamespace = "http://soap.service.lab.epam.com/", wsdlLocation = "http://localhost:8090/calc?wsdl")
public class CalcServiceImplService
    extends Service
{

    private final static URL CALCSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CALCSERVICEIMPLSERVICE_QNAME = new QName("http://soap.service.lab.epam.com/", "CalcServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/calc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CALCSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CalcServiceImplService() {
        super(__getWsdlLocation(), CALCSERVICEIMPLSERVICE_QNAME);
    }

    public CalcServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCSERVICEIMPLSERVICE_QNAME, features);
    }

    public CalcServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCSERVICEIMPLSERVICE_QNAME);
    }

    public CalcServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCSERVICEIMPLSERVICE_QNAME, features);
    }

    public CalcServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalcServiceImpl
     */
    @WebEndpoint(name = "CalcServiceImplPort")
    public CalcServiceImpl getCalcServiceImplPort() {
        return super.getPort(new QName("http://soap.service.lab.epam.com/", "CalcServiceImplPort"), CalcServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcServiceImpl
     */
    @WebEndpoint(name = "CalcServiceImplPort")
    public CalcServiceImpl getCalcServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.service.lab.epam.com/", "CalcServiceImplPort"), CalcServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CALCSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CALCSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
